### ISSUE TITLE
Multiple Ingresses

### ISSUE THREAD

**Issue by michelefa1988** [regulaforensics/helm-charts#5]
Can you please add the option to add more than 1 ingress please?

I have an issue where I would like to secure regula apis for the public but keep them open on an internal ingress. This requires me to add 2 ingresses.

Thanks

**Comment by AndreiPaulau** [comment]
Hello @michelefa1988!

We haven't seen such charts with multiple ingresses yet. Would be great if you can share something for the reference, since you're most probably using such one.

Many thanks!

**Comment by michelefa1988** [comment]
@AndreiPaulau  if I do a PR for this will be able to check it and approve it?

**Comment by michelefa1988** [comment]
@AndreiPaulau  I use something like this
```
# extraIngresses:
#   - name: noName
#     ingressClassName: "nginx"
#     annotations:
#       cert-manager.io/cluster-issuer: "prod"
#       nginx.ingress.kubernetes.io/ssl-redirect: "true" 
#       nginx.ingress.kubernetes.io/rewrite-target: "/$1"
#     hosts:
#       - host: example.com
#         paths: ["/webhooks/(.*)"]
#     tls: 
#       - secretName: example.com
#         hosts:
#           - example.com
```

**Comment by AndreiPaulau** [comment]
Hello,

First of all sorry for late reply.

Unfortunatelly, from perspective of BP this is not a common approach. This doesn't bring up much value rather than adds additional complexity.
The best workaround would be to have a separate custom Ingress resource yaml in addition to the exisitng helm chart, wich could be adopted at any situation on your side to allign to your needs at any moment.
